name: Trigger Repo Update

on:
  release:
    types: [published, unpublished, created, edited, deleted]
  workflow_dispatch: 

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.VRSL_VPM_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'AcChosen',
              repo: 'vrsl-vpm',
              workflow_id: 'build-listing.yml',
              ref: 'main',
            })

# thanks to bd_ for this action: https://github.com/bdunderscore/modular-avatar/blob/main/.github/workflows/trigger-repo-rebuild.yml
